[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Build only the required packages, and individually
precise-builds = true
# Generate and dist a source tarball
source-tarball = false
# CI backends to support
ci = "github"
github-build-setup = "build-setup.yml"
# Whether to enable GitHub Attestations
github-attestations = true
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Which actions to run on pull requests
pr-run-mode = "plan"
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.7-prerelease.1"

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-15"
x86_64-apple-darwin = "macos-13"
x86_64-unknown-linux-gnu = "ubuntu-24.04"

[dist.bin-aliases]
# legacy alias kept intentionally? Replace with server-blueprint-cli if used
